name: Python CI

on: 
 push:
  branches:["main"]
 pull_request:
  branches:["main']
 workflow_dispatch:
jobs:
 build:
  runs_on: ubuntu_latest
 steps:

  -name: Run a one line script 
   run:echo Hello world 
  
 
  
